<?php $captcha = $this->getCaptchaModel() ?>
<?php $theme = $captcha->getTheme(); ?>
<script type="text/javascript">
    var onloadCallback = function () {
        grecaptcha.render('recaptcha_html_element', {
            <?php if($theme == 'invisible'):?>
            "size": "invisible",
            'callback': function (response) {
                // since there are multiple instances of the response text area, populate them all with this response.
                // this then will ensure teh correct response is submitted back for this request
                $$('.g-recaptcha-response').each(function (elm) {
                    $(elm).innerText = response;
                });
                $$('.enable-captcha-clicked').each(function (elm) {
                    elm.enable();
                });
                loginForm._submit();
            },
            <?php endif; ?>
            'sitekey': '<?php echo $captcha->getPublicKey(); ?>'
        });
    };
</script>
<br/>
<div id="recaptcha_html_element" style="clear: both"></div>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit&hl=<?php echo $captcha->getLanguage(); ?>" async defer></script>
<?php if($theme == 'invisible'):?>
    <script>
            Validation.prototype.onSubmit = Validation.prototype.onSubmit.wrap(function(parentMethod,ev){
                Event.stop(ev);
                grecaptcha.execute($('recaptcha_html_element'));
                $('recaptcha_html_element').select('iframe').each(function (iframe) {
                    iframe.writeAttribute('tabindex', '-1');
                });
                return false;
            });

    </script>
<?php endif; ?>
